ALTER TABLE saas_settings 
ADD COLUMN IF NOT EXISTS maintenance_mode BOOLEAN DEFAULT false,
ADD COLUMN IF NOT EXISTS plan_starter_price NUMERIC DEFAULT 0,
ADD COLUMN IF NOT EXISTS plan_pro_price NUMERIC DEFAULT 149000,
ADD COLUMN IF NOT EXISTS plan_enterprise_price NUMERIC DEFAULT 499000;
